name: Build and Deploy to Azure

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Allow manual deployment

permissions:
  packages: write  # ✅ Allow pushing Docker images to GHCR
  contents: read   # ✅ Allow workflow access to repo contents

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry (GHCR)
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin

      - name: Build Docker image
        run: |
          docker build -t ghcr.io/gammelgaard52/securefileexchange:latest -f backend/Dockerfile .

      - name: Push Docker image to GHCR
        run: |
          docker push ghcr.io/gammelgaard52/securefileexchange:latest

  deploy-to-azure:
    needs: build-and-push  # Deploy only after the image is pushed
    runs-on: ubuntu-latest

    steps:
      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Web App (app-tdcsft)
        run: |
          az webapp config container set --name app-tdcsft --resource-group rg-tdcsft \
          --docker-custom-image-name ghcr.io/gammelgaard52/securefileexchange:latest
